version: '3.9'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    env_file:
      - ./.env.sample
    ports:
      - 3306:3306
  testlink:
    image: 'bitnami/testlink:latest'
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mariadb
    env_file:
      - ./.env.sample
